<a href="https://colab.research.google.com/github/Swap02-droid/tensorflow-deep-learning/blob/main/Fundamentals_of_tensors_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using tensorflow

More specifically, we're going to cover:
* Introduction of tensor
* Getting information for tensor
* Manipulating tensor
* Tensors and NumPy
* Using @tf.function
* Using GPU with tensorflow (or TPUs)

In [ ]:
print("welcome to google colabs")

welcome to google colabs


In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
# lets check number of dimensions of a scalar (ndim stands for number of dimension)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# letes dimension of vector
vector.ndim

1

In [ ]:
# Lets create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check dimension of our matrix
matrix.ndim

2

In [ ]:
# create one more matrix
another_matrix = tf.constant([[10., 7,],
                              [7., 10.]], dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [ ]:
  # what is the number of dimension of matrix
  another_matrix.ndim

2

In [ ]:
# lets create tensor
tensor = tf.constant([[[1, 2, 3],
                       [2,3,4]],
                      [[1,2,3],
                       [2,3,4]],
                      [[4,5,6],
                       [5,6,7]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]],

       [[4, 5, 6],
        [5, 6, 7]]], dtype=int32)>

In [ ]:
# now check dimension of tensor
tensor.ndim

3

Whate we've created so far:
* scelar: a single number
* vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of number
* tensor: an n-dimensional array of number (when n can be any number)

### creating a tensor with `tf.Variable`

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Lets creating same tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Lets try to change one of the element of our changeable_tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# how about we try .assign()
changeable_tensor[0].assign(3)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 7], dtype=int32)>

In [ ]:
# now lets try with unchangeable_tensor
unchangeable_tensor[0].assig(3)

AttributeError: ignored

#### here we are, In Neural Networks some time you might want to changes tensor. So you have to decide which tensor you want to take which is tf.constant() or tf.Variable()

### lets look into random tensor with
* create two random (but the same) tensor

In [ ]:
random_1 = tf.random.Generator.from_seed(8) # set seed for reproducibility
random_1 = random_1.normal(shape=[3, 2])
random_2 = tf.random.Generator.from_seed(4+4)
random_2 = random_2.normal(shape=[3, 2])
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.69211644,  0.84215707],
        [-0.06378496,  0.92800784],
        [-0.6039789 , -0.1766927 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.69211644,  0.84215707],
        [-0.06378496,  0.92800784],
        [-0.6039789 , -0.1766927 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
### lets preform the some oprarion to check how tensor works (with constant)

a = tf.constant(1)
b = tf.constant(1)
x = tf.add(a, b)
with tf.compat.v1.Session() as sess:
  x.eval()

NotImplementedError: ignored

### shuffle the order of element in a tensor

In [ ]:
not_shuffle_tensor = tf.constant([[10, 7],
                                  [3, 6],
                                  [11, 9]])

not_shuffle_tensor.ndim

2

In [ ]:
not_shuffle_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  6],
       [11,  9]], dtype=int32)>

In [ ]:
shuffle_tensor = tf.random.shuffle(not_shuffle_tensor)
shuffle_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11,  9],
       [10,  7],
       [ 3,  6]], dtype=int32)>

In [ ]:
tf.random.set_seed(3) # globle level random seed
tf.random.shuffle(not_shuffle_tensor, seed=3)   # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  6],
       [10,  7],
       [11,  9]], dtype=int32)>

### lets see other ways to create tensors

In [ ]:
## letes create ones in tensor
tf.ones([3, 5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
## lets create zeros in tensors
tf.zeros(shape=(2, 5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
## You can also turn NumPy arrays into tesnor, lets see how we can
import numpy as np
tensor_A = np.arange(1, 25, dtype=np.int32)
tensor_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(tensor_A, shape=(2,12)) ## simply we pass tensor_A as values
B = tf.constant(tensor_A)
A, B

(<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### get some information about tensors

In [ ]:
# create tensor
tensor_info = tf.zeros(shape=[2, 3, 4, 5])  # its 4 dimension tensor / another name is rank
tensor_info

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor_info[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
print("shape of tensor_info:- ", tensor_info.shape), print("dimensions of tensor_info:-", tensor_info.ndim), print("size of tensor_info:- ", tf.size(tensor_info)), print("size of tensor_info in NumPy:- ", tf.size(tensor_info).numpy())

shape of tensor_info:-  (2, 3, 4, 5)
dimensions of tensor_info:- 4
size of tensor_info:-  tf.Tensor(120, shape=(), dtype=int32)
size of tensor_info in NumPy:-  120


(None, None, None, None)

### indexing of tensors

In [ ]:
tensor_info[:1]

<tf.Tensor: shape=(1, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor_info[:2, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
# rank_3_tensor (3 dimensions)

rank_3_tensor = tf.constant([[[1, 2, 3,],
                             [4, 5, 6]],
                            [[6, 7, 8],
                             [9, 2, 4]]])
rank_3_tensor[1:2, 1:1, :2]

<tf.Tensor: shape=(1, 0, 2), dtype=int32, numpy=array([], shape=(1, 0, 2), dtype=int32)>

In [ ]:

rank_2_tensor_ = tf.constant([[[1, 2, 3,],
                             [4, 5, 6],
                              [1,2,3]],
                            [[6, 7, 8],
                             [9, 2, 4],
                             [1, 4, 5]]])
rank_2_tensor_

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]],

       [[6, 7, 8],
        [9, 2, 4],
        [1, 4, 5]]], dtype=int32)>

In [ ]:
tensor_2_3_rank = tf.constant([[1,2,6],
                               [3,4,5]])
tensor_2_3_rank

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 6],
       [3, 4, 5]], dtype=int32)>

## Manupulating Tensor (tensor operation)

Basic Operations
***
+, -, *, /
***

In [ ]:
random_tensor = tf.constant([[10, 7],
                             [3, 9]])
random_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  9]], dtype=int32)>

In [ ]:
# you can add values in tensor using the addition operation

random_tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 19]], dtype=int32)>

In [ ]:
# orinal tensor is
random_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  9]], dtype=int32)>

In [ ]:
# Multiplication also works in tensor
random_tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  90]], dtype=int32)>

In [ ]:
# tensor provides us a functions to do same operations
tf.math.multiply(random_tensor, 10), tf.math.add(random_tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  90]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 19]], dtype=int32)>)

**Matrix Multiplication**

In ML, Matrix Multilication is most comman tensor operations

In [ ]:
x = tf.constant([[10, 7],
                 [3, 6],
                 [4, 8]])

y = tf.constant([[2, 2, 3],
                 [3, 4, 4]])

In [ ]:
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  6],
        [ 4,  8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 2, 3],
        [3, 4, 4]], dtype=int32)>)

In [ ]:
tf.matmul(x, y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[41, 48, 58],
       [24, 30, 33],
       [32, 40, 44]], dtype=int32)>

In [ ]:
x * y

InvalidArgumentError: ignored

In [ ]:
def add_number(num):
  sum = 0
  while (num>0):
    sum += num%10
    num = num//10
    if (num==0 and sum>9):
      num = sum
      sum = 0
  return sum

In [ ]:
add_number(987)

6

In [ ]:
def check(string):
  clean_string = string.lower()

  left_str, right_str = 0, len(clean_string)-1
  while left_str < right_str:
    if clean_string[left_str] != clean_string[right_str]:
      return False

    left_str +=1
    right_str -=1


  return True

check("nitins")


False

In [ ]:
## Panlindrome patter
def pattern_palindrom():
  for i in range(1, int(input())):
    print(int(ascii(1)*i)**2)

pattern_palindrom()

5
1
121
12321
1234321


In [ ]:
def add_three(lst):
  sum_lst = []
  second_index = 1
  last_index = len(lst) - 1

  for i in range(len(lst)):
    print("i", lst[i], "second_index", lst[second_index], "last_index", lst[last_index])
    sum = lst[i] + lst[second_index] + lst[last_index]
    print("sum", sum)
    if sum == 0:
      sum_lst.append([lst[i], lst[second_index], lst[last_index]])
    second_index =i+1
  print(sum_lst)

add_three([-2, -1, 0, 1, 2])

i -2 second_index -1 last_index 2
sum -1
i -1 second_index -1 last_index 2
sum 0
i 0 second_index 0 last_index 2
sum 2
i 1 second_index 1 last_index 2
sum 4
i 2 second_index 2 last_index 2
sum 6
[[-1, -1, 2]]
