<a href="https://colab.research.google.com/github/Swap02-droid/tensorflow-deep-learning/blob/main/Fundamentals_of_tensors_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor Aggregatoin (Find the min, max, mean and more)

Aggregation tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
# Get the absolute values

s = tf.constant([-7, -10])
s

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(s)  # or in python we can use abs() function only

# If you see here all nigative values are converted into positive

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Lets go through the following forms of aggregations



*   Get the minimum
*   Get the maximum
*   Get the men of tensor
*   Get the sum of tensor





In [ ]:
# Create a random tensors between 0-100 with size of 50

random_tensor = tf.constant(np.random.randint(0, 100, size=50))
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([16, 49, 11, 71, 64, 57, 54, 27,  7, 12, 88, 39, 11, 65,  0, 54, 59,
       31, 27, 67, 81, 73,  6, 22, 68, 16, 26, 37,  7, 57,  1, 66, 24, 95,
       86, 76, 14, 16, 99,  0, 79, 43, 86, 10, 70, 44, 14, 61, 11, 21])>

In [ ]:
random_tensor.ndim, tf.size(random_tensor), random_tensor.shape

(1, <tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]))

In [ ]:
# Find the minimum
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find the maximum
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Find the mean
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Find the sum
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2118>

In [ ]:
# lest check how we can find veriance, here we are using tensorflow probability. If you are working with TensorFlow Probability and need to compute the sample variance, you can use tfp.stats.variance
import tensorflow_probability as tfp


tfp.stats.variance(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=847>

In [ ]:
# now lets check how we can find verianve with the help of tf.math.reduce_variance()

# tensor_for_variance = tf.cast(random_tensor, tf.float32)

tf.math.reduce_variance(tf.cast(random_tensor, dtype=tf.float32))  # If you see here the out is queit different from tensor probability

# Note:- if you are working with TensorFlow core operations and just need to compute the variance of a tensor, you can use tf.math.reduce_variance

<tf.Tensor: shape=(), dtype=float32, numpy=847.75037>

In [ ]:
#Lest find Standard deviavtion
tf.math.reduce_std(tf.cast(random_tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.116154>

### Find the positional min and max


In [ ]:
# Create a new tensor for positional min and max
tf.random.set_seed(20)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.78914285, 0.47340286, 0.39979064, 0.730348  , 0.65567374,
       0.95290804, 0.1569767 , 0.876413  , 0.42520928, 0.6074914 ,
       0.5420697 , 0.8619175 , 0.6087326 , 0.25354815, 0.02741039,
       0.807798  , 0.4440137 , 0.9375683 , 0.20025587, 0.9634783 ,
       0.8950304 , 0.56499386, 0.2593336 , 0.7975584 , 0.4932909 ,
       0.92441773, 0.26945102, 0.177073  , 0.35694516, 0.54103565,
       0.231601  , 0.71623254, 0.07930815, 0.59971976, 0.42030382,
       0.9922309 , 0.6451732 , 0.4512868 , 0.0813998 , 0.8110639 ,
       0.9847126 , 0.32717872, 0.94470954, 0.0367533 , 0.4858843 ,
       0.6560893 , 0.15126693, 0.7843076 , 0.50933826, 0.3634901 ],
      dtype=float32)>

In [ ]:
# To find positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.027410388>

In [ ]:
# To find positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9922309>

### Squeezing a tenso (remove all the single dimensions)



In [ ]:
# creating a tensor
tf.random.set_seed(20)
squeezed_tensor = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,1,1,50))
squeezed_tensor


<tf.Tensor: shape=(1, 1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[[0.78914285, 0.47340286, 0.39979064, 0.730348  ,
             0.65567374, 0.95290804, 0.1569767 , 0.876413  ,
             0.42520928, 0.6074914 , 0.5420697 , 0.8619175 ,
             0.6087326 , 0.25354815, 0.02741039, 0.807798  ,
             0.4440137 , 0.9375683 , 0.20025587, 0.9634783 ,
             0.8950304 , 0.56499386, 0.2593336 , 0.7975584 ,
             0.4932909 , 0.92441773, 0.26945102, 0.177073  ,
             0.35694516, 0.54103565, 0.231601  , 0.71623254,
             0.07930815, 0.59971976, 0.42030382, 0.9922309 ,
             0.6451732 , 0.4512868 , 0.0813998 , 0.8110639 ,
             0.9847126 , 0.32717872, 0.94470954, 0.0367533 ,
             0.4858843 , 0.6560893 , 0.15126693, 0.7843076 ,
             0.50933826, 0.3634901 ]]]]]]], dtype=float32)>

In [ ]:
squeezed_tensor.shape

TensorShape([1, 1, 1, 1, 1, 1, 50])

In [ ]:
# Removes dimensions of size 1 from the shape of a tensor.
tensor = tf.squeeze(squeezed_tensor)
tensor.shape

TensorShape([50])

### One hot encoding in tensorflow

In [ ]:
# lets create a list some list
some_list = [0, 1, 2, 3]
one_hot = tf.one_hot(some_list, depth=4)
one_hot

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
indices = [0, 1, 2, 3]
depth = 3
random_one_hot = tf.one_hot(indices, depth, on_value = 0.5, off_value = 0.0, axis=-1)

random_one_hot

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5],
       [0. , 0. , 0. ]], dtype=float32)>

In [ ]:
tf.random.set_seed(30)
random_tensor = tf.constant(tf.random.uniform(shape=[50], minval=40, maxval=800, dtype=tf.int64))
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([547, 275, 740, 410, 563, 604, 571, 164, 305, 661, 450, 295, 142,
       247, 181,  82, 535, 151, 135, 439, 620,  98, 465, 250, 518, 137,
        43, 560, 281, 368, 358, 462, 433, 227, 521, 272, 421, 563,  56,
       796, 448, 606, 115,  50, 586, 500,  41, 471, 358, 742])>

In [ ]:
random_tensor_one_hot = tf.one_hot(random_tensor, depth = 10)
random_tensor_one_hot

<tf.Tensor: shape=(50, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0.,

In [ ]:
random_list = [[123, 435, 2342, 533, 434, 234, 576, 7656],
               [576, 435, 234, 7656, 854, 2342, 123, 434]]
random_tensor_one_hot = tf.one_hot(random_list, depth = 2343)
random_tensor_one_hot



<tf.Tensor: shape=(2, 8, 2343), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>

In [ ]:
random_tensor_one_hot[0][tf.argmax(random_tensor_one_hot[0])]

TypeError: ignored

In [ ]:
random_list = [[1, 3, 2, 5, 4, 2, 6, 7],
               [2, 5, 6, 5, 7, 5, 7, 4]]

random_tensor_one_hot = tf.one_hot(random_list, depth=8)
print(random_tensor_one_hot)

tf.Tensor(
[[[0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1. 0. 0. 0.]]], shape=(2, 8, 8), dtype=float32)
